// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6GL3GdpbI2E-QSXOQV8-H7dkjQWHDHo',
    appId: '1:670916699526:web:862934cce9b9fc24d07807',
    messagingSenderId: '670916699526',
    projectId: 'flutter-firebase-crud-7ccb2',
    authDomain: 'flutter-firebase-crud-7ccb2.firebaseapp.com',
    storageBucket: 'flutter-firebase-crud-7ccb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPlhDG_68yaV736FGqbu65X8ypyAnWn8',
    appId: '1:670916699526:android:ae0dc9a0c9ea0c95d07807',
    messagingSenderId: '670916699526',
    projectId: 'flutter-firebase-crud-7ccb2',
    storageBucket: 'flutter-firebase-crud-7ccb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCybgOTlavIxr-9DJytnyZqvfliQ_g18',
    appId: '1:670916699526:ios:6ff888d1a6cacd9cd07807',
    messagingSenderId: '670916699526',
    projectId: 'flutter-firebase-crud-7ccb2',
    storageBucket: 'flutter-firebase-crud-7ccb2.appspot.com',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfCybgOTlavIxr-9DJytnyZqvfliQ_g18',
    appId: '1:670916699526:ios:ba6ea602974974ccd07807',
    messagingSenderId: '670916699526',
    projectId: 'flutter-firebase-crud-7ccb2',
    storageBucket: 'flutter-firebase-crud-7ccb2.appspot.com',
    iosBundleId: 'com.example.flutterCrudFirebase.RunnerTests',
  );
}
